"""added type column

Revision ID: f06d23164eca
Revises: 1e018506c35f
Create Date: 2026-03-02 18:15:59.354985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f06d23164eca'
down_revision: Union[str, Sequence[str], None] = '1e018506c35f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repair_items', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repair_items', 'type')
    # ### end Alembic commands ###
