name: Deploy Vicecar

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 5.181.109.142
          username: localadmin
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/vicecar_tma
            git pull origin main
            source .venv/bin/activate
            pip install -r requirements.txt
            alembic upgrade head
            sudo systemctl restart vicecar